include:
  # QWERTY BT (Bluetooth / ワイヤレス版)
  - board: nice_nano_v2
    shield: charybdis_left
    keymap: qwerty
    format: bt
    artifact-name: charybdis_qwerty_left
    # ↓ Bluetooth版のフォルダを明示的に指定してエラーを回避します
    cmake-args: -DZMK_EXTRA_MODULES="${GITHUB_WORKSPACE}/boards/shields/charybdis-bt"

  - board: nice_nano_v2
    shield: charybdis_right
    keymap: qwerty
    format: bt
    artifact-name: charybdis_qwerty_right
    snippet: studio-rpc-usb-uart
    # ↓ 右手側も同様に指定します
    cmake-args: -DZMK_EXTRA_MODULES="${GITHUB_WORKSPACE}/boards/shields/charybdis-bt"

  # Firmware Reset (設定リセット用)
  - board: nice_nano_v2
    shield: settings_reset
    format: reset
    artifact-name: firmware_reset_nano_v2
